language: go

go:
  - "1.10.x"

# - master

os: linux

sudo: false
install:
    - go get -t

script: 
    - go build .
    - ./test/go-unit-tests.sh
    - ./build.sh linux
    - ./test/mock/defaults-change.sh
    - ./test/mock/short-versions.sh
    - ./test/mock/direct-paths.sh
    - /test/mock/expected_ports.sh
    # - ./test/mock/port-clash.sh sparse
    - ./test/docker-test.sh $(cat .build/VERSION)

after_success:
    - echo "Build Successful!"

after_failure:
    - echo "Build Failed!"
